Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # use Ubuntu 14.04 box
  config.vm.box = "ubuntu/trusty64"

  # Synced folder setup
  config.vm.synced_folder "./", "/home/vagrant"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # VirtualBox provider-specific configuration:
  config.vm.provider "virtualbox" do |vb|
    # VM name
    vb.name = "FlyingSquid-Ubuntu14.04-Trusty64"

    # Display the VirtualBox GUI when booting the machine
    vb.gui = false

    # Customize the amount of memory and CPUs on the VM
    vb.memory = "1024"
    vb.cpus = 2
  end

  # Enable provisioning with a shell script
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get upgrade -y
    sudo apt-get install -y git \
                            autoconf \
                            automake \
                            build-essential \
                            make \
                            pkg-config \
                            libtool \
                            libssl-dev \
                            tcl-dev \
                            libexpat-dev \
                            libpcre3 libpcre3-dev \
                            libcap-dev \
                            flex \
                            hwloc \
                            lua5.2 \
                            libncurses-dev \
                            curl \
                            dos2unix \
                            libcurl4-openssl-dev
  SHELL
  
end
